name: Create Release

on:
  push:
    tags:
      - "v*.*.*" # Triggers on version tags like v1.0.0, v2.1.3, etc.
  workflow_dispatch: # Allow manual triggering

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build CSS from LESS
        run: yarn grunt

      - name: Create bbzcal directory structure
        run: |
          mkdir -p build/bbzcal

      - name: Copy source files to bbzcal folder
        run: |
          # Copy all files except build directory and .git
          rsync -av --exclude='build/' \
                    --exclude='.git/' \
                    . build/bbzcal/

      - name: Create release zip
        run: |
          cd build
          zip -r bbzcal-release.zip bbzcal/

      - name: Get version from tag or generate timestamp
        id: version
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
          else
            VERSION=$(date +'%Y.%m.%d-%H%M%S')
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.version.outputs.version }}
          name: BBZ Calendar Plugin ${{ steps.version.outputs.version }}
          body: |
            ## BBZ Calendar Plugin Release ${{ steps.version.outputs.version }}

            This release contains the complete BBZ Calendar Moodle plugin source code.

            ### Installation
            1. Download the `bbzcal-release.zip` file
            2. Extract it to your Moodle installation's `local/` directory
            3. Navigate to Site Administration > Notifications to complete the installation

            ### What's included
            - All PHP source files
            - Compiled CSS styles
            - Language files
            - Database schema
            - Templates

          files: |
            build/bbzcal-release.zip
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
